# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: API_test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x"]
        os: [ubuntu-latest]
        mongodb-version: [4.2]
        node-version: [12.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno ${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions
          
      - name: Setup NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Setup MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Newman
        run: npm install --prefic tests/API/

      - name: Cache Dependencies
        run: deno cache server.ts

      - name: Run API and Postman's tests
        run: |
          deno run --allow-env --allow-read --allow-net server.ts &
          sleep 2
          cd tests/API && ./node_modules/newman/bin/newman.js run API.postman_collection.json
          kill -9 `lsof -i:3000 -t`
